[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader']

[phases.build]
cmds = [
  'php artisan storage:link || true',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'heroku-php-apache2 public/'